### ISSUE TITLE
Add Windows Support: Replace fcntl with Windows-Compatible Alternative

### ISSUE THREAD

**Issue by krondelsina** [yoori/flare-bypasser#1]
Hello,

I am trying to run the project on a Windows machine, but I encountered the following error:

ModuleNotFoundError: No module named 'fcntl'

The fcntl module is not available on Windows, as it is specific to UNIX-based systems (Linux/macOS). Could you please add support for Windows by either replacing fcntl with a compatible alternative or using conditional imports that only load fcntl on UNIX systems?

Thank you!

**Comment by dataflowjs** [comment]
@krondelsina hello, can you provide the minimal not working code that you have?

**Comment by yoori** [comment]
Try latest version - I switched to use uvicorn (instead gunicorn) on win32

**Comment by jacket430** [comment]
Still unable to run on Windows, creating a docker container also doesn't work as it has issues finding the files in their respective directories (mainly .sh files). Any chance you could publish the container to docker so we could download it directly? Building it doesn't seem to work for me. I'm going to try it in WSL, which I'm sure will work, but it would be nice to not have to.

**Comment by yoori** [comment]
Please try latest version
[This commit](https://github.com/yoori/flare-bypasser/commit/86f9caa6c044e49d47836313466e578f44b351e6) should help (I tested after it version on windows)
