### ISSUE TITLE
ModuleNotFoundError: No module named 'certifi'

### ISSUE THREAD

**Issue by Ed3n18** [yoori/flare-bypasser#12]
Hey,

Im trying to run it but it always stops at the same Error.
Tried using the source code and pip package method but they both fail.

Im using Windows Server 2025, Build 26311.5000
Terminal with PowerShell 7.4.6

![Screenshot 2024-11-10 122950](https://github.com/user-attachments/assets/6921671f-935c-47bd-a53d-2dcda34faf91)

**Comment by yoori** [comment]
[I fixed installation for windows pip](https://github.com/yoori/flare-bypasser/commit/86f9caa6c044e49d47836313466e578f44b351e6),
Try latest version.

**Comment by Ed3n18** [comment]
It now runs without issues.

Is there any chance you can make it work with Prowlarr?

![image](https://github.com/user-attachments/assets/00e2966c-4ab8-4b21-ba14-b377fb06b323)
![image](https://github.com/user-attachments/assets/46d9d1d6-e945-4719-85d7-c575f2ba4e70)

**Comment by yoori** [comment]
Please try version after [this fix](https://github.com/yoori/flare-bypasser/commit/20aafe87a1fd9dc71a95e1ef839c4c518f8dc71c)
