### ISSUE TITLE
Make compatible with prowlarr

### ISSUE THREAD

**Issue by yoori** [yoori/flare-bypasser#13]
It now runs without issues.

Is there any chance you can make it work with Prowlarr?

![image](https://github.com/user-attachments/assets/00e2966c-4ab8-4b21-ba14-b377fb06b323)
![image](https://github.com/user-attachments/assets/46d9d1d6-e945-4719-85d7-c575f2ba4e70)

_Originally posted by @Ed3n18 in https://github.com/yoori/flare-bypasser/issues/12#issuecomment-2466921626_

**Comment by yoori** [comment]
Please try version after [this fix](https://github.com/yoori/flare-bypasser/commit/20aafe87a1fd9dc71a95e1ef839c4c518f8dc71c)

**Comment by Ed3n18** [comment]
With the Newest Source Code:
![image](https://github.com/user-attachments/assets/3bfdb528-b4e7-48fc-a37f-0b1d58d622c8)
![image](https://github.com/user-attachments/assets/5dae8a9d-d1b1-4952-990f-f659bda49ba4)

Prowlarr Logs:
![image](https://github.com/user-attachments/assets/5f577e5f-e7d9-4f4e-a063-5b8918fd3e22)

If you need anything else let me know

**Comment by yoori** [comment]
Will check at near time, need to review flaresolverr proxy passing format

**Comment by yoori** [comment]
Please, try version with [this fix](https://github.com/yoori/flare-bypasser/commit/8bf233c0f8f3e4fa87925c0884d804ba086d4665)

**Comment by Ed3n18** [comment]
Latest Source Code:
![image](https://github.com/user-attachments/assets/ba47a866-2d8a-4cba-8a45-b5c9faceef18)

![image](https://github.com/user-attachments/assets/8e462032-2d1f-4637-a0bb-01e7bae9edd6)

**Comment by yoori** [comment]
Please, try version after [this fix](https://github.com/yoori/flare-bypasser/commit/a77599fdfa8178ea21320aae5298420f01a4bc00)

**Comment by Ed3n18** [comment]
It works! Awesome, thank you!
