### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dangelo352** [yoori/flare-bypasser#15]
{'status': 'error', 'message': "Error: Error solving the challenge. On platform win32 at step 'browser init': 'NoneType' object has no attribute 'closed'", 'startTimestamp': 1731644906.417136, 'endTimestamp': 1731644906.894636}
PS C:\Users\DAngelo\test>

**Comment by yoori** [comment]
Please, try latest version (here few fixes in nodriver, that can generate this error), if problem will be reproduced please provide docker logs (command: docker compose logs) or service output if you run without docker

**Comment by Xoncia** [comment]
it's an issue in nodriver, hasn't been updated in ages.

**Comment by yoori** [comment]
@Xoncia , yep, nodriver have much problems :(
we switched to zendriver for more productive stabilization process (zendriver already contains part of my fixes, and few additional fixes in MR on review)
