### ISSUE TITLE
Ability to configure server port

### ISSUE THREAD

**Issue by gacek1123** [yoori/flare-bypasser#19]
Is it possible to change the server port? If not, could we get this feature?

**Comment by yoori** [comment]
Hi,
If you run docker - set port in docker-compose.yml instead 20080
If you run flare_bypass_server, you can pass : `-b 0.0.0.0:8080` (replace 8080 with required port)

**Comment by TeusDev** [comment]
just a tip, for extreme newbies like me u can add a mention in readme that the link will be localhost:20080 that will already avoid any newcomers to how docker works too
