### ISSUE TITLE
added proxy authethication support

### ISSUE THREAD

**Issue by Xoncia** [yoori/flare-bypasser#2]
i figured out how to integrate proxy support into your code, also I'd like to talk to you about the addition of request.post

**Comment by yoori** [comment]
Hi, I added support of proxy authorization (over gost - will be installed in docker, and need to install if you use bypasser as package). Don't think that plugin usage (like in flaresolverr) is good idea, because it can be detected.
Processing of post requests in progress ...

**Comment by yoori** [comment]
Hi, POST supported

**Comment by Xoncia** [comment]
Oh yes I see, that's great, I ran into problems with residential proxies like 
http://user:pass@ip but good shit
I will use this version once I'm on my setup again. Thanks

**Comment by yoori** [comment]
Ok, give me to know if some problems will be detected.
