### ISSUE TITLE
Timeout While Trying to Solve Captcha

### ISSUE THREAD

**Issue by dmryce** [yoori/flare-bypasser#27]
I am running your arm64 image in docker and when trying to solve a captcha it eventually fails with a timeout error. I've checked the debug directory, but there is no relevant information in the folder. My docker log with debug turned on is attached.
Any idea what's happening here? Thank you.

[flare-bypasser log.txt](https://github.com/user-attachments/files/17987098/flare-bypasser.log.txt)

**Comment by yoori** [comment]
Please, try latest version after [this fix](https://github.com/yoori/flare-bypasser/commit/ef46dc721424204212f3c77b72bf38775a0cb8e3)
