### ISSUE TITLE
How to use flare-bypasser with proxy?

### ISSUE THREAD

**Issue by Duoquote** [yoori/flare-bypasser#28]
As far as I have seen, there is no example for how to use proxy with flare-bypasser, how can I use proxies with it? Also I am using the docker image, do I just pass `proto://user:pass@host:port` with the request or something?

**Comment by yoori** [comment]
Example of usage proxy parameter:
`curl -XPOST 'http://localhost:20080/get_cookies' -H 'Content-Type: application/json' --data-raw '{"maxTimeout": 60000, "url": "https://torrentleech.pl/login.php?returnto=%2F", "proxy": "<PROXY URL WITH AUTH>"}'`
