### ISSUE TITLE
Don't work in docker on Mac m3

### ISSUE THREAD

**Issue by Coun1er** [yoori/flare-bypasser#4]
Hi!

```
2024-11-06 23:16:16 flare-bypasser  | Download chrome by url: https://storage.googleapis.com/chrome-for-testing-public/130.0.6669.0/linux64/chrome-linux64.zip
2024-11-06 23:16:56 flare-bypasser  | Run server (extensions = )
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [24] [INFO] Starting gunicorn 23.0.0
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [24] [INFO] Listening at: http://0.0.0.0:8080 (24)
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [24] [INFO] Using worker: uvicorn.workers.UvicornWorker
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [33] [INFO] Booting worker with pid: 33
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [33] [INFO] Started server process [33]
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [33] [INFO] Waiting for application startup.
2024-11-06 23:16:56 flare-bypasser  | [2024-11-06 20:16:56 +0000] [33] [INFO] Application startup complete.
2024-11-06 23:17:36 flare-bypasser  | 2024-11-06 20:17:36,322 [nodriver.core.browser] [INFO]: starting
2024-11-06 23:17:36 flare-bypasser  | executable :/usr/bin/chrome
2024-11-06 23:17:36 flare-bypasser  | 
2024-11-06 23:17:36 flare-bypasser  | arguments:
2024-11-06 23:17:36 flare-bypasser  | --remote-allow-origins=*
2024-11-06 23:17:36 flare-bypasser  | --no-first-run
2024-11-06 23:17:36 flare-bypasser  | --no-service-autorun
2024-11-06 23:17:36 flare-bypasser  | --no-default-browser-check
2024-11-06 23:17:36 flare-bypasser  | --homepage=about:blank
2024-11-06 23:17:36 flare-bypasser  | --no-pings
2024-11-06 23:17:36 flare-bypasser  | --password-store=basic
2024-11-06 23:17:36 flare-bypasser  | --disable-infobars
2024-11-06 23:17:36 flare-bypasser  | --disable-breakpad
2024-11-06 23:17:36 flare-bypasser  | --disable-component-update
2024-11-06 23:17:36 flare-bypasser  | --disable-backgrounding-occluded-windows
2024-11-06 23:17:36 flare-bypasser  | --disable-renderer-backgrounding
2024-11-06 23:17:36 flare-bypasser  | --disable-background-networking
2024-11-06 23:17:36 flare-bypasser  | --disable-dev-shm-usage
2024-11-06 23:17:36 flare-bypasser  | --disable-features=IsolateOrigins,site-per-process
2024-11-06 23:17:36 flare-bypasser  | --disable-session-crashed-bubble
2024-11-06 23:17:36 flare-bypasser  | --disable-search-engine-choice-screen
2024-11-06 23:17:36 flare-bypasser  | --user-data-dir=/tmp/uc_ha9w843o
2024-11-06 23:17:36 flare-bypasser  | --disable-features=IsolateOrigins,site-per-process
2024-11-06 23:17:36 flare-bypasser  | --disable-session-crashed-bubble
2024-11-06 23:17:36 flare-bypasser  | --no-sandbox
2024-11-06 23:17:36 flare-bypasser  | --remote-debugging-host=127.0.0.1
2024-11-06 23:17:36 flare-bypasser  | --remote-debugging-port=58921
2024-11-06 23:17:39 flare-bypasser  | 2024-11-06 20:17:39,117 [root] [INFO]: Close webdriver
2024-11-06 23:17:39 flare-bypasser  | 2024-11-06 20:17:39,117 [root] [ERROR]: Error solving the challenge. On step 'solving': \n                ---------------------\n                Failed to connect to browser\n                ---------------------\n                One of the causes could be when you are running as root.\n                In that case you need to pass no_sandbox=True \n                
2024-11-06 23:17:39 flare-bypasser  | Error solving the challenge. On step 'solving': \n                ---------------------\n                Failed to connect to browser\n                ---------------------\n                One of the causes could be when you are running as root.\n                In that case you need to pass no_sandbox=True \n                
2024-11-06 23:17:39 flare-bypasser  | Traceback (most recent call last):
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 249, in _resolve_challenge
2024-11-06 23:17:39 flare-bypasser  |     self._driver = await BrowserWrapper.create(use_proxy)
2024-11-06 23:17:39 flare-bypasser  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 70, in create
2024-11-06 23:17:39 flare-bypasser  |     nodriver_driver = await nodriver.start(
2024-11-06 23:17:39 flare-bypasser  |                       ^^^^^^^^^^^^^^^^^^^^^
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/nodriver/core/util.py", line 96, in start
2024-11-06 23:17:39 flare-bypasser  |     return await Browser.create(config)
2024-11-06 23:17:39 flare-bypasser  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 91, in create
2024-11-06 23:17:39 flare-bypasser  |     await instance.start()
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 352, in start
2024-11-06 23:17:39 flare-bypasser  |     raise Exception(
2024-11-06 23:17:39 flare-bypasser  | Exception: 
2024-11-06 23:17:39 flare-bypasser  |                 ---------------------
2024-11-06 23:17:39 flare-bypasser  |                 Failed to connect to browser
2024-11-06 23:17:39 flare-bypasser  |                 ---------------------
2024-11-06 23:17:39 flare-bypasser  |                 One of the causes could be when you are running as root.
2024-11-06 23:17:39 flare-bypasser  |                 In that case you need to pass no_sandbox=True 
2024-11-06 23:17:39 flare-bypasser  |                 
2024-11-06 23:17:39 flare-bypasser  | 
2024-11-06 23:17:39 flare-bypasser  | During handling of the above exception, another exception occurred:
2024-11-06 23:17:39 flare-bypasser  | 
2024-11-06 23:17:39 flare-bypasser  | Traceback (most recent call last):
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypass_server.py", line 82, in process_solve_request
2024-11-06 23:17:39 flare-bypasser  |     solve_response = await solver.solve(solve_request)
2024-11-06 23:17:39 flare-bypasser  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 224, in solve
2024-11-06 23:17:39 flare-bypasser  |     res = await self._resolve_challenge(req)
2024-11-06 23:17:39 flare-bypasser  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 23:17:39 flare-bypasser  |   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 267, in _resolve_challenge
2024-11-06 23:17:39 flare-bypasser  |     raise Solver.Exception(error_message)
2024-11-06 23:17:39 flare-bypasser  | flare_bypasser.flare_bypasser.Solver.Exception: Error solving the challenge. On step 'solving': \n                ---------------------\n                Failed to connect to browser\n                ---------------------\n                One of the causes could be when you are running as root.\n                In that case you need to pass no_sandbox=True \n                
2024-11-06 23:17:39 flare-bypasser  | 

```

Don't work in docker on Mac m1( 
What could be wrong? 
I just do git clone flare-bypasse and docker compose up -d

**Comment by yoori** [comment]
Give me day, I will check on mac

**Comment by Coun1er** [comment]
> Give me day, I will check on mac

yes of course

**Comment by Coun1er** [comment]
On Ubuntu 22 in docker everything worked right away

**Comment by parthpatel643** [comment]
Encountered similar error after building the docker image:

Host: Raspberry Pi 4 hosting Debian Bullseye.

```python
[2024-11-07 10:28:30 +0000] [24] [INFO] Starting gunicorn 23.0.0
[2024-11-07 10:28:30 +0000] [24] [INFO] Listening at: http://0.0.0.0:8080 (24)
[2024-11-07 10:28:30 +0000] [24] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-11-07 10:28:30 +0000] [29] [INFO] Booting worker with pid: 29
[2024-11-07 10:28:30 +0000] [29] [INFO] Started server process [29]
[2024-11-07 10:28:30 +0000] [29] [INFO] Waiting for application startup.
[2024-11-07 10:28:30 +0000] [29] [INFO] Application startup complete.
2024-11-07 10:28:33,228 [nodriver.core.browser] [INFO]: starting
	executable :/usr/bin/chrome

arguments:
--remote-allow-origins=*
	--no-first-run
	--no-service-autorun
	--no-default-browser-check
	--homepage=about:blank
	--no-pings
	--password-store=basic
	--disable-infobars
	--disable-breakpad
	--disable-component-update
	--disable-backgrounding-occluded-windows
	--disable-renderer-backgrounding
	--disable-background-networking
	--disable-dev-shm-usage
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--disable-search-engine-choice-screen
	--user-data-dir=/tmp/uc_ip13lh75
	--disable-features=IsolateOrigins,site-per-process
	--disable-session-crashed-bubble
	--no-sandbox
	--remote-debugging-host=127.0.0.1
	--remote-debugging-port=59555
2024-11-07 10:28:33,242 [root] [INFO]: Close webdriver
2024-11-07 10:28:33,243 [root] [ERROR]: Error solving the challenge. On step 'solving': [Errno 8] Exec format error: '/usr/bin/chrome'
```

**Comment by yoori** [comment]
@Coun1er
Sorry, I tried on macos (but not m1) - and it works.
M. b. you have specific problem with chrome running on your gpu - and I need help with this.
Can you please : update project from repo, uncomment `CHECK_SYSTEM: true` parameter in docker-compose.yml , build/up docker and provide `docker logs`

**Comment by yoori** [comment]
Additionally you can try to run with CHROME_DISABLE_GPU: true (uncomment it in docker-compose.yml),
I think, this can help

**Comment by parthpatel643** [comment]
> Encountered similar error after building the docker image:
> 
> Host: Raspberry Pi 4 hosting Debian Bullseye.
> 
> ```python
> [2024-11-07 10:28:30 +0000] [24] [INFO] Starting gunicorn 23.0.0
> [2024-11-07 10:28:30 +0000] [24] [INFO] Listening at: http://0.0.0.0:8080 (24)
> [2024-11-07 10:28:30 +0000] [24] [INFO] Using worker: uvicorn.workers.UvicornWorker
> [2024-11-07 10:28:30 +0000] [29] [INFO] Booting worker with pid: 29
> [2024-11-07 10:28:30 +0000] [29] [INFO] Started server process [29]
> [2024-11-07 10:28:30 +0000] [29] [INFO] Waiting for application startup.
> [2024-11-07 10:28:30 +0000] [29] [INFO] Application startup complete.
> 2024-11-07 10:28:33,228 [nodriver.core.browser] [INFO]: starting
> 	executable :/usr/bin/chrome
> 
> arguments:
> --remote-allow-origins=*
> 	--no-first-run
> 	--no-service-autorun
> 	--no-default-browser-check
> 	--homepage=about:blank
> 	--no-pings
> 	--password-store=basic
> 	--disable-infobars
> 	--disable-breakpad
> 	--disable-component-update
> 	--disable-backgrounding-occluded-windows
> 	--disable-renderer-backgrounding
> 	--disable-background-networking
> 	--disable-dev-shm-usage
> 	--disable-features=IsolateOrigins,site-per-process
> 	--disable-session-crashed-bubble
> 	--disable-search-engine-choice-screen
> 	--user-data-dir=/tmp/uc_ip13lh75
> 	--disable-features=IsolateOrigins,site-per-process
> 	--disable-session-crashed-bubble
> 	--no-sandbox
> 	--remote-debugging-host=127.0.0.1
> 	--remote-debugging-port=59555
> 2024-11-07 10:28:33,242 [root] [INFO]: Close webdriver
> 2024-11-07 10:28:33,243 [root] [ERROR]: Error solving the challenge. On step 'solving': [Errno 8] Exec format error: '/usr/bin/chrome'
> Error solving the challenge. On step 'solving': [Errno 8] Exec format error: '/usr/bin/chrome'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 248, in _resolve_challenge
>     self._driver = await BrowserWrapper.create(use_proxy)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 70, in create
>     nodriver_driver = await nodriver.start(
>                       ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/nodriver/core/util.py", line 96, in start
>     return await Browser.create(config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 91, in create
>     await instance.start()
>   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 325, in start
>     await asyncio.create_subprocess_exec(
>   File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 223, in create_subprocess_exec
>     transport, protocol = await loop.subprocess_exec(
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1708, in subprocess_exec
>     transport = await self._make_subprocess_transport(
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
>     transp = _UnixSubprocessTransport(self, protocol, args, shell,
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
>     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
>   File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 818, in _start
>     self._proc = subprocess.Popen(
>                  ^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: '/usr/bin/chrome'
> ```

rebuild the docker with commit 2a4ee10a52ea1b9e788b8603308cca4fca86a8cc

```yaml
services:
  flare-bypasser :
    build:
      args:
        CHROME_VERSION: '130.'
        UID: 1001
        CHROME_DISABLE_GPU: true
        CHECK_SYSTEM: true
        # PYTHON_VERSION: 3.11
      context: .
      dockerfile: Dockerfile
    container_name: flare-bypasser
    image: flare-bypasser:v0.1
    ports:
      - 20080:8080
    #volumes:
      #- ./var:/opt/flare_bypasser/var/
      #< Uncomment if you persistent logs between runs
      #- ./examples/custom_user_commands/:/opt/flare_bypasser/extensions/
      #< Uncomment for run with extension example (/command/my-click uri)
```

```python
Chrome diagnostic failed (chrome running)
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process

```

**Comment by yoori** [comment]
> > Encountered similar error after building the docker image:
> > Host: Raspberry Pi 4 hosting Debian Bullseye.
> > ```python
> > [2024-11-07 10:28:30 +0000] [24] [INFO] Starting gunicorn 23.0.0
> > [2024-11-07 10:28:30 +0000] [24] [INFO] Listening at: http://0.0.0.0:8080 (24)
> > [2024-11-07 10:28:30 +0000] [24] [INFO] Using worker: uvicorn.workers.UvicornWorker
> > [2024-11-07 10:28:30 +0000] [29] [INFO] Booting worker with pid: 29
> > [2024-11-07 10:28:30 +0000] [29] [INFO] Started server process [29]
> > [2024-11-07 10:28:30 +0000] [29] [INFO] Waiting for application startup.
> > [2024-11-07 10:28:30 +0000] [29] [INFO] Application startup complete.
> > 2024-11-07 10:28:33,228 [nodriver.core.browser] [INFO]: starting
> > 	executable :/usr/bin/chrome
> > 
> > arguments:
> > --remote-allow-origins=*
> > 	--no-first-run
> > 	--no-service-autorun
> > 	--no-default-browser-check
> > 	--homepage=about:blank
> > 	--no-pings
> > 	--password-store=basic
> > 	--disable-infobars
> > 	--disable-breakpad
> > 	--disable-component-update
> > 	--disable-backgrounding-occluded-windows
> > 	--disable-renderer-backgrounding
> > 	--disable-background-networking
> > 	--disable-dev-shm-usage
> > 	--disable-features=IsolateOrigins,site-per-process
> > 	--disable-session-crashed-bubble
> > 	--disable-search-engine-choice-screen
> > 	--user-data-dir=/tmp/uc_ip13lh75
> > 	--disable-features=IsolateOrigins,site-per-process
> > 	--disable-session-crashed-bubble
> > 	--no-sandbox
> > 	--remote-debugging-host=127.0.0.1
> > 	--remote-debugging-port=59555
> > 2024-11-07 10:28:33,242 [root] [INFO]: Close webdriver
> > 2024-11-07 10:28:33,243 [root] [ERROR]: Error solving the challenge. On step 'solving': [Errno 8] Exec format error: '/usr/bin/chrome'
> > Error solving the challenge. On step 'solving': [Errno 8] Exec format error: '/usr/bin/chrome'
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/flare_bypasser.py", line 248, in _resolve_challenge
> >     self._driver = await BrowserWrapper.create(use_proxy)
> >                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/site-packages/flare_bypasser/browser_wrapper.py", line 70, in create
> >     nodriver_driver = await nodriver.start(
> >                       ^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/site-packages/nodriver/core/util.py", line 96, in start
> >     return await Browser.create(config)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 91, in create
> >     await instance.start()
> >   File "/usr/local/lib/python3.11/site-packages/nodriver/core/browser.py", line 325, in start
> >     await asyncio.create_subprocess_exec(
> >   File "/usr/local/lib/python3.11/asyncio/subprocess.py", line 223, in create_subprocess_exec
> >     transport, protocol = await loop.subprocess_exec(
> >                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1708, in subprocess_exec
> >     transport = await self._make_subprocess_transport(
> >                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 207, in _make_subprocess_transport
> >     transp = _UnixSubprocessTransport(self, protocol, args, shell,
> >              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 36, in __init__
> >     self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
> >   File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 818, in _start
> >     self._proc = subprocess.Popen(
> >                  ^^^^^^^^^^^^^^^^^
> >   File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > OSError: [Errno 8] Exec format error: '/usr/bin/chrome'
> > ```
> 
> rebuild the docker with commit [2a4ee10](https://github.com/yoori/flare-bypasser/commit/2a4ee10a52ea1b9e788b8603308cca4fca86a8cc)
> 
> ```yaml
> services:
>   flare-bypasser :
>     build:
>       args:
>         CHROME_VERSION: '130.'
>         UID: 1001
>         CHROME_DISABLE_GPU: true
>         CHECK_SYSTEM: true
>         # PYTHON_VERSION: 3.11
>       context: .
>       dockerfile: Dockerfile
>     container_name: flare-bypasser
>     image: flare-bypasser:v0.1
>     ports:
>       - 20080:8080
>     #volumes:
>       #- ./var:/opt/flare_bypasser/var/
>       #< Uncomment if you persistent logs between runs
>       #- ./examples/custom_user_commands/:/opt/flare_bypasser/extensions/
>       #< Uncomment for run with extension example (/command/my-click uri)
> ```
> 
> ```python
> Chrome diagnostic failed (chrome running)
> /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
> /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process
> ```

Please, can you show me result of execution : `docker exec -it flare-bypasser arch` (with upped container)

**Comment by parthpatel643** [comment]
> > 
> > 
> > rebuild the docker with commit [2a4ee10](https://github.com/yoori/flare-bypasser/commit/2a4ee10a52ea1b9e788b8603308cca4fca86a8cc)
> > ```yaml
> > services:
> >   flare-bypasser :
> >     build:
> >       args:
> >         CHROME_VERSION: '130.'
> >         UID: 1001
> >         CHROME_DISABLE_GPU: true
> >         CHECK_SYSTEM: true
> >         # PYTHON_VERSION: 3.11
> >       context: .
> >       dockerfile: Dockerfile
> >     container_name: flare-bypasser
> >     image: flare-bypasser:v0.1
> >     ports:
> >       - 20080:8080
> >     #volumes:
> >       #- ./var:/opt/flare_bypasser/var/
> >       #< Uncomment if you persistent logs between runs
> >       #- ./examples/custom_user_commands/:/opt/flare_bypasser/extensions/
> >       #< Uncomment for run with extension example (/command/my-click uri)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > Chrome diagnostic failed (chrome running)
> > /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
> > /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process
> > ```
> 
> Please, can you show me result of execution : `docker exec -it flare-bypasser arch` (with upped container)

my board is arm64 `aarch64`.

also the container quits as soon as it starts. rebuilt the image on commit 8aff21b0d1008d09e4fb5f2b70bc6d6faff69794

```python
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                      PORTS     NAMES
1f6cebd3bc66   flare-bypasser:0.1.25   "/usr/bin/dumb-init …"   45 seconds ago   Exited (1) 42 seconds ago             flare-bypasser
user@domain:/home/pi/flare-bypasser# docker logs 1f6cebd3bc66
Chrome diagnostic failed (chrome running)
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
/opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process
```

**Comment by yoori** [comment]
> > > rebuild the docker with commit [2a4ee10](https://github.com/yoori/flare-bypasser/commit/2a4ee10a52ea1b9e788b8603308cca4fca86a8cc)
> > > ```yaml
> > > services:
> > >   flare-bypasser :
> > >     build:
> > >       args:
> > >         CHROME_VERSION: '130.'
> > >         UID: 1001
> > >         CHROME_DISABLE_GPU: true
> > >         CHECK_SYSTEM: true
> > >         # PYTHON_VERSION: 3.11
> > >       context: .
> > >       dockerfile: Dockerfile
> > >     container_name: flare-bypasser
> > >     image: flare-bypasser:v0.1
> > >     ports:
> > >       - 20080:8080
> > >     #volumes:
> > >       #- ./var:/opt/flare_bypasser/var/
> > >       #< Uncomment if you persistent logs between runs
> > >       #- ./examples/custom_user_commands/:/opt/flare_bypasser/extensions/
> > >       #< Uncomment for run with extension example (/command/my-click uri)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```python
> > > Chrome diagnostic failed (chrome running)
> > > /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
> > > /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process
> > > ```
> > 
> > 
> > Please, can you show me result of execution : `docker exec -it flare-bypasser arch` (with upped container)
> 
> my board is arm64 `aarch64`.
> 
> also the container quits as soon as it starts. rebuilt the image on commit [8aff21b](https://github.com/yoori/flare-bypasser/commit/8aff21b0d1008d09e4fb5f2b70bc6d6faff69794)
> 
> ```python
> CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                      PORTS     NAMES
> 1f6cebd3bc66   flare-bypasser:0.1.25   "/usr/bin/dumb-init …"   45 seconds ago   Exited (1) 42 seconds ago             flare-bypasser
> user@domain:/home/pi/flare-bypasser# docker logs 1f6cebd3bc66
> Chrome diagnostic failed (chrome running)
> /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 21: /usr/bin/chrome: cannot execute binary file: Exec format error
> /opt/flare_bypasser/bin/FlareBypasserRun.sh: line 86: kill: (21) - No such process
> ```

Thanks ! I commited fix (download chrome for required architecture) - can you check ?

**Comment by Coun1er** [comment]
On the latest version on Mac I have problems with paths when installing chrome:

```
➜  flare-bypasser git:(main) docker compose up -d
[+] Running 1/1
 ! flare-bypasser Warning pull access denied for flare-bypasser, repository does not exist or may req...                        13.9s
[+] Building 89.1s (12/23)                                                                                       docker:desktop-linux
 => [flare-bypasser internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 3.77kB                                                                                           0.0s
 => [flare-bypasser internal] load metadata for docker.io/library/python:3.11-slim-bullseye                                      9.3s
 => [flare-bypasser internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                                  0.0s
 => [flare-bypasser internal] load build context                                                                                 0.0s
 => => transferring context: 202.07kB                                                                                            0.0s
 => [flare-bypasser builder 1/8] FROM docker.io/library/python:3.11-slim-bullseye@sha256:08ef1d5c4e0c05244f0971150437c57f6c7986  0.0s
 => CACHED [flare-bypasser builder 2/8] WORKDIR /app/                                                                            0.0s
 => CACHED [flare-bypasser builder 3/8] RUN mkdir -p "/packages"   && apt-get update   && apt-get install -y --no-install-recom  0.0s
 => CACHED [flare-bypasser builder 4/8] RUN apt-get install -y --no-install-recommends curl  # gost-install.sh requirement       0.0s
 => CACHED [flare-bypasser builder 5/8] COPY utils/gost-install.sh ./gost-install.sh                                             0.0s
 => CACHED [flare-bypasser builder 6/8] RUN ./gost-install.sh --install                                                          0.0s
 => CACHED [flare-bypasser builder 7/8] COPY utils/linux_chrome_installer.py /opt/flare_bypasser/bin/linux_chrome_installer.py   0.0s
 => ERROR [flare-bypasser builder 8/8] RUN python3 /opt/flare_bypasser/bin/linux_chrome_installer.py   --version-prefix="130."  79.8s
------
 > [flare-bypasser builder 8/8] RUN python3 /opt/flare_bypasser/bin/linux_chrome_installer.py   --version-prefix="130."   --install-root=/opt/flare_bypasser/installed_chrome/   --arch=$(arch) ||   { echo "Can't install chrome (required version '130.')" >&2 ; exit 1 ; }:
4.171 Download chrome by url: https://storage.googleapis.com/chrome-for-testing-public/130.0.6669.0/mac-arm64/chrome-mac-arm64.zip
79.55 ERROR:root:Can't install chrome: [Errno 2] No such file or directory: '/opt/flare_bypasser/installed_chrome/chrome'
79.56 Can't install chrome (required version '130.')
------
failed to solve: process "/bin/sh -c python3 /opt/flare_bypasser/bin/linux_chrome_installer.py   --version-prefix=\"$CHROME_VERSION\"   --install-root=/opt/flare_bypasser/installed_chrome/   --arch=$(arch) ||   { echo \"Can't install chrome (required version '$CHROME_VERSION')\" >&2 ; exit 1 ; }" did not complete successfully: exit code: 1
```

**Comment by rimallo** [comment]
yoori thanks for quick fixes. have same issue on m2. tried with latest commit - no luck :(

**Comment by yoori** [comment]
@rimallo can you provide log (of docker)

**Comment by rimallo** [comment]
> @rimallo can you provide log (of docker)

```=> ERROR [flare-bypasser builder 10/10] RUN . /tmp/build.env ; if [ "$(arch)" != "x86_64" ] ; then     echo "To install chrome(131.) from google repository (no archive versions for ARM)" ;     chmod  6.6s
------
 > [flare-bypasser builder 10/10] RUN . /tmp/build.env ; if [ "$(arch)" != "x86_64" ] ; then     echo "To install chrome(131.) from google repository (no archive versions for ARM)" ;     chmod +x ./linux_chrome_deb_repo_installer.sh ;     bash -c "./linux_chrome_deb_repo_installer.sh /opt/flare_bypasser/installed_chrome/ '131.'" ||     { echo "Can't install chrome (required version '131.')" >&2 ; exit 1 ; } ;   else     echo "To install chrome(131.) from archive" ;     mkdir -p /opt/flare_bypasser/installed_chrome/usr/bin/ ;     python3 ./linux_chrome_archive_installer.py       --version-prefix="131."       --install-root=/opt/flare_bypasser/installed_chrome/usr/bin/       --arch=$(arch) ||     { echo "Can't install chrome (required version '131.')" >&2 ; exit 1 ; } ;   fi:
0.109 To install chrome(131.) from google repository (no archive versions for ARM)
5.943 To install package: google-chrome-stable=131.0.6778.69-1
6.543 Chrome install failed:
6.544
6.544 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
6.544
6.544 E: Unable to locate package google-chrome-stable
6.544 Available versions:
6.544 cat: /tmp/available_chrome_versions: No such file or directory
6.545 Can't install chrome (required version '131.')
------
failed to solve: process "/bin/sh -c . /tmp/build.env ; if [ \"$(arch)\" != \"x86_64\" ] ; then     echo \"To install chrome($CHROME_VERSION) from google repository (no archive versions for ARM)\" ;     chmod +x ./linux_chrome_deb_repo_installer.sh ;     bash -c \"./linux_chrome_deb_repo_installer.sh /opt/flare_bypasser/installed_chrome/ '$CHROME_VERSION'\" ||     { echo \"Can't install chrome (required version '$CHROME_VERSION')\" >&2 ; exit 1 ; } ;   else     echo \"To install chrome($CHROME_VERSION) from archive\" ;     mkdir -p /opt/flare_bypasser/installed_chrome/usr/bin/ ;     python3 ./linux_chrome_archive_installer.py       --version-prefix=\"$CHROME_VERSION\"       --install-root=/opt/flare_bypasser/installed_chrome/usr/bin/       --arch=$(arch) ||     { echo \"Can't install chrome (required version '$CHROME_VERSION')\" >&2 ; exit 1 ; } ;   fi" did not complete successfully: exit code: 1```

**Comment by yoori** [comment]
Please, try latest version - after [this fix](https://github.com/yoori/flare-bypasser/commit/7e687f502418535cdb0942d7f2bc92198d60057b)
I tested on m3 - it should work

**Comment by nelzomal** [comment]
hi @yoori 
I am using Mac M3. I start the server using docker, then run the example python code, 

get this error

{"status":"error","message":"Error: On user-agent getting: \n                ---------------------\n                Failed to connect to browser\n                ---------------------\n                One of the causes could be when you are running as root.\n                In that case you need to pass no_sandbox=True\n                Browser error output:/usr/lib/chromium/chromium: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory\n","startTimestamp":1734831424.554683,"endTimestamp":1734831427.340671}

**Comment by cellulosa** [comment]
on Mac mini M2.

With

```
        CHROME_DISABLE_GPU: true
        CHECK_SYSTEM: true
```

I get:

```
Starting system message bus: dbus.
Chrome diagnostic failed (chrome running)
/usr/lib/chromium/chromium: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
Removing stale PID file /var/run/dbus/pid..
```

Wihtout, it was throwing this other error:

```
Failed to connect to browser
One of the causes could be when you are running as root.
In that case you need to pass no_sandbox=True
Browser error output:/usr/lib/chromium/chromium: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
```
